-- 코드를 작성해주세요
select 
    CASE 
        WHEN   
            1<=MONTH(DIFFERENTIATION_DATE) AND MONTH(DIFFERENTIATION_DATE)<=3 THEN '1Q'
        WHEN
            4<=MONTH(DIFFERENTIATION_DATE) AND MONTH(DIFFERENTIATION_DATE)<=6 THEN '2Q'
        WHEN
            6<=MONTH(DIFFERENTIATION_DATE) AND MONTH(DIFFERENTIATION_DATE)<=9 THEN '3Q'
        ELSE '4Q'
         END AS QUARTER,
    COUNT(DIFFERENTIATION_DATE) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY CASE 
        WHEN   
            1<=MONTH(DIFFERENTIATION_DATE) AND MONTH(DIFFERENTIATION_DATE)<=3 THEN '1Q'
        WHEN
            4<=MONTH(DIFFERENTIATION_DATE) AND MONTH(DIFFERENTIATION_DATE)<=6 THEN '2Q'
        WHEN
            6<=MONTH(DIFFERENTIATION_DATE) AND MONTH(DIFFERENTIATION_DATE)<=9 THEN '3Q'
        ELSE '4Q'
         END
ORDER BY QUARTER